### ISSUE TITLE
Synchronous Option?

### ISSUE THREAD

**Issue by joshuapinter** [wwayne/react-native-user-defaults#7]
Hi There, 

Great, easy-to-use library!

I'm curious what your thoughts are on having a synchronous option. I think it would be valuable for certain circumstances. 

For example, I'm storing whether or not a user has seen the Welcome tutorial of an app so I would like to retrieve this preference synchronously and hold off on displaying anything until that is complete.

What do you think?

**Comment by wwayne** [comment]
Sorry I'm not familiar with iOS developing, so I'm not able to provide you with some ideas. But I think operating on user defaults is sync, using callback and promise here is just because it is more JS :)

**Comment by joshuapinter** [comment]
I think you're right @wwayne. It seems awkward using async for User Defaults but you're right, it's just how Javascript (and React Native's bridge) operates. 

Closing for now. :)
